language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g gulp-cli
script: 
  - gulp build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
notifications:
  slack:
    rooms:
      - some-test-more:q5fOEFA9utjq0ASObvyeW53z#general
      - some-test-more:q5fOEFA9utjq0ASObvyeW53z#random
					